/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_kevinbanegas;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    private int xMouse;
    private int yMouse;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_2 = new javax.swing.JPanel();
        bg_3 = new javax.swing.JPanel();
        text_empresa = new javax.swing.JLabel();
        text_sesion = new javax.swing.JLabel();
        text_usuario = new javax.swing.JLabel();
        text_contra = new javax.swing.JLabel();
        bg_1 = new javax.swing.JPanel();
        field_usuario = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();
        barra = new javax.swing.JPanel();
        exittxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg_2.setBackground(new java.awt.Color(255, 255, 255));
        bg_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_3.setBackground(new java.awt.Color(0, 102, 153));

        text_empresa.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        text_empresa.setForeground(new java.awt.Color(255, 255, 255));
        text_empresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_empresa.setText("APEX LEGENDS");

        javax.swing.GroupLayout bg_3Layout = new javax.swing.GroupLayout(bg_3);
        bg_3.setLayout(bg_3Layout);
        bg_3Layout.setHorizontalGroup(
            bg_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bg_3Layout.setVerticalGroup(
            bg_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(text_empresa)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        bg_2.add(bg_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        text_sesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        text_sesion.setForeground(new java.awt.Color(255, 255, 255));
        text_sesion.setText("INICIAR SESION");
        bg_2.add(text_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        text_usuario.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        text_usuario.setForeground(new java.awt.Color(0, 0, 0));
        text_usuario.setText("USUARIO");
        bg_2.add(text_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        text_contra.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        text_contra.setForeground(new java.awt.Color(0, 0, 0));
        text_contra.setText("CONTRASEÑA");
        bg_2.add(text_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        bg_1.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout bg_1Layout = new javax.swing.GroupLayout(bg_1);
        bg_1.setLayout(bg_1Layout);
        bg_1Layout.setHorizontalGroup(
            bg_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        bg_1Layout.setVerticalGroup(
            bg_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bg_2.add(bg_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 520, 50));

        field_usuario.setBackground(new java.awt.Color(255, 255, 255));
        field_usuario.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        field_usuario.setForeground(new java.awt.Color(102, 102, 102));
        field_usuario.setText("Ingrese su nombre de usuario");
        field_usuario.setBorder(null);
        field_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                field_usuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                field_usuarioMousePressed(evt);
            }
        });
        field_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_usuarioActionPerformed(evt);
            }
        });
        bg_2.add(field_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 450, 30));

        contra.setBackground(new java.awt.Color(255, 255, 255));
        contra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contra.setForeground(new java.awt.Color(102, 102, 102));
        contra.setText("********");
        contra.setBorder(null);
        contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraMousePressed(evt);
            }
        });
        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });
        bg_2.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 450, -1));

        barra.setBackground(new java.awt.Color(255, 255, 255));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });

        exittxt.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        exittxt.setForeground(new java.awt.Color(102, 102, 102));
        exittxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exittxt.setText("X");
        exittxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exittxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exittxtMouseDragged(evt);
            }
        });
        exittxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exittxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exittxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exittxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exittxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addComponent(exittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg_2.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INGRESAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg_2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg_2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg_2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground( new Color(0,51,153));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        new Main(field_usuario.getText(),String.valueOf(contra.getPassword())).setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void exittxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMousePressed

    }//GEN-LAST:event_exittxtMousePressed

    private void exittxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseExited
        exittxt.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_exittxtMouseExited

    private void exittxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseEntered
        exittxt.setForeground(Color.RED);
    }//GEN-LAST:event_exittxtMouseEntered

    private void exittxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exittxtMouseClicked

    private void exittxtMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseDragged

    }//GEN-LAST:event_exittxtMouseDragged

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed

    private void contraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraMousePressed
        if(field_usuario.getText().isEmpty()){
            field_usuario.setText("Ingrese su nombre de usuario");
            field_usuario.setForeground(Color.DARK_GRAY);
        }

        if(String.valueOf(contra.getPassword()).equals("********")){
            contra.setText("");
            contra.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_contraMousePressed

    private void contraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraMouseClicked

    }//GEN-LAST:event_contraMouseClicked

    private void field_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_usuarioActionPerformed

    private void field_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field_usuarioMousePressed
        if(field_usuario.getText().equals("Ingrese su nombre de usuario")){
            field_usuario.setText("");
            field_usuario.setForeground(Color.DARK_GRAY);
        }

        if(String.valueOf(contra.getPassword()).isEmpty()){
            contra.setText("********");
            contra.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_field_usuarioMousePressed

    private void field_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field_usuarioMouseClicked

    }//GEN-LAST:event_field_usuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JPanel bg_1;
    private javax.swing.JPanel bg_2;
    private javax.swing.JPanel bg_3;
    private javax.swing.JPasswordField contra;
    private javax.swing.JLabel exittxt;
    private javax.swing.JTextField field_usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text_contra;
    private javax.swing.JLabel text_empresa;
    private javax.swing.JLabel text_sesion;
    private javax.swing.JLabel text_usuario;
    // End of variables declaration//GEN-END:variables
}
