package examen1p2_kevinbanegas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

public class Main extends javax.swing.JFrame {

    private int loocupo = 0;
    private String usuario;
    private String contra;
    private ArrayList<Jugadores> jugadores = new ArrayList();
    private ArrayList<Personajes> personajes = new ArrayList();
    private ArrayList<Armas> armas = new ArrayList();

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContra() {
        return contra;
    }

    public void setContra(String contra) {
        this.contra = contra;
    }

    @Override
    public String toString() {
        return "Main{" + "usuario=" + usuario + ", contra=" + contra + '}';
    }

    public Main(String usuario, String contra) {
        initComponents();
        this.usuario = usuario;
        this.contra = contra;
        jugadores.add(0, new Jugadores(this.usuario, this.contra));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void generar() {
        jugadores.add(new Jugadores("CactusKevin", "eidfjay"));
        jugadores.add(new Jugadores("Sham", "oidyysnt"));
        jugadores.add(new Jugadores("kimberly", "danoaeysa"));

        armas.add(new Armas("LazarBeam", 30));
        armas.add(new Armas("AR", 10));
        armas.add(new Armas("Shawty", 20));

        personajes.add(new Fortaleza("PeaceFinder", armas.get(0)));
        personajes.add(new Medico("AntiDeath", armas.get(1)));
        personajes.add(new Rastraeador("TrackerDUH", armas.get(2)));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_white = new javax.swing.JPanel();
        panelMain = new javax.swing.JTabbedPane();
        pan_Select = new javax.swing.JPanel();
        cb_personajes = new javax.swing.JComboBox<>();
        pan_seleccionar = new javax.swing.JPanel();
        label_seleccionar = new javax.swing.JLabel();
        pan_Jugar = new javax.swing.JPanel();
        pantalla = new javax.swing.JScrollPane();
        texto_partida = new javax.swing.JTextArea();
        label_restantes = new javax.swing.JLabel();
        botton_start = new javax.swing.JButton();
        field_atacar = new javax.swing.JFormattedTextField();
        boton_atacar = new javax.swing.JButton();
        pan_CrearPersonaje = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_white.setBackground(new java.awt.Color(255, 255, 255));

        panelMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelMainStateChanged(evt);
            }
        });

        cb_personajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pan_seleccionar.setBackground(new java.awt.Color(0, 204, 0));
        pan_seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pan_seleccionarMouseClicked(evt);
            }
        });

        label_seleccionar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_seleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_seleccionar.setText("Seleccionar");

        javax.swing.GroupLayout pan_seleccionarLayout = new javax.swing.GroupLayout(pan_seleccionar);
        pan_seleccionar.setLayout(pan_seleccionarLayout);
        pan_seleccionarLayout.setHorizontalGroup(
            pan_seleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_seleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        pan_seleccionarLayout.setVerticalGroup(
            pan_seleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_seleccionarLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(label_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout pan_SelectLayout = new javax.swing.GroupLayout(pan_Select);
        pan_Select.setLayout(pan_SelectLayout);
        pan_SelectLayout.setHorizontalGroup(
            pan_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_SelectLayout.createSequentialGroup()
                .addGroup(pan_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_SelectLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cb_personajes, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_SelectLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(pan_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pan_SelectLayout.setVerticalGroup(
            pan_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_SelectLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb_personajes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(pan_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        panelMain.addTab("tab1", pan_Select);

        texto_partida.setColumns(20);
        texto_partida.setRows(5);
        pantalla.setViewportView(texto_partida);

        label_restantes.setText("Restantes: 60");

        botton_start.setText("COMENZAR");
        botton_start.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                botton_startStateChanged(evt);
            }
        });
        botton_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botton_startMouseClicked(evt);
            }
        });

        field_atacar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        boton_atacar.setText("ATACAR");
        boton_atacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_atacarMouseClicked(evt);
            }
        });
        boton_atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_JugarLayout = new javax.swing.GroupLayout(pan_Jugar);
        pan_Jugar.setLayout(pan_JugarLayout);
        pan_JugarLayout.setHorizontalGroup(
            pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_JugarLayout.createSequentialGroup()
                .addGroup(pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_JugarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pantalla))
                    .addGroup(pan_JugarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(botton_start)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_restantes)))
                .addContainerGap())
            .addGroup(pan_JugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field_atacar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_atacar)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        pan_JugarLayout.setVerticalGroup(
            pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_JugarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_restantes)
                    .addComponent(botton_start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_atacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_atacar))
                .addContainerGap())
        );

        panelMain.addTab("tab2", pan_Jugar);

        javax.swing.GroupLayout pan_CrearPersonajeLayout = new javax.swing.GroupLayout(pan_CrearPersonaje);
        pan_CrearPersonaje.setLayout(pan_CrearPersonajeLayout);
        pan_CrearPersonajeLayout.setHorizontalGroup(
            pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        pan_CrearPersonajeLayout.setVerticalGroup(
            pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        panelMain.addTab("tab3", pan_CrearPersonaje);

        javax.swing.GroupLayout bg_whiteLayout = new javax.swing.GroupLayout(bg_white);
        bg_white.setLayout(bg_whiteLayout);
        bg_whiteLayout.setHorizontalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_whiteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        bg_whiteLayout.setVerticalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_whiteLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_white, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_white, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelMainStateChanged
        if (loocupo == 0) {
            generar();
            loocupo = 1;
        }
        if (panelMain.getSelectedIndex() == 0) {
            DefaultComboBoxModel m = new DefaultComboBoxModel();
            for (Personajes personaje : personajes) {
                m.addElement(personaje);
            }
            cb_personajes.setModel(m);
        }
    }//GEN-LAST:event_panelMainStateChanged

    private void pan_seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_seleccionarMouseClicked
        jugadores.get(0).setPersonaje((Personajes) cb_personajes.getSelectedItem());
        panelMain.setSelectedIndex(1);

    }//GEN-LAST:event_pan_seleccionarMouseClicked

    private void botton_startStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botton_startStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_startStateChanged

    private void botton_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botton_startMouseClicked
        jugadores.get(0).setPersonaje((Personajes) cb_personajes.getSelectedItem());
        for (int i = 4; i < 60; i++) {
            jugadores.add(new Jugadores(personajes));

        }
        for (Jugadores jugadore : jugadores) {
            texto_partida.append(jugadore.toString() + "\n");

        }

    }//GEN-LAST:event_botton_startMouseClicked

    private void boton_atacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_atacarActionPerformed

    private void boton_atacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_atacarMouseClicked
        
    }//GEN-LAST:event_boton_atacarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main("bruh", "ksjdk").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_white;
    private javax.swing.JButton boton_atacar;
    private javax.swing.JButton botton_start;
    private javax.swing.JComboBox<String> cb_personajes;
    private javax.swing.JFormattedTextField field_atacar;
    private javax.swing.JLabel label_restantes;
    private javax.swing.JLabel label_seleccionar;
    private javax.swing.JPanel pan_CrearPersonaje;
    private javax.swing.JPanel pan_Jugar;
    private javax.swing.JPanel pan_Select;
    private javax.swing.JPanel pan_seleccionar;
    private javax.swing.JTabbedPane panelMain;
    private javax.swing.JScrollPane pantalla;
    private javax.swing.JTextArea texto_partida;
    // End of variables declaration//GEN-END:variables
}
