package examen1p2_kevinbanegas;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    private int loocupo = 0;
    private String usuario;
    private String contra;
    private ArrayList<Jugadores> jugadores = new ArrayList();
    private ArrayList<Personajes> personajes = new ArrayList();
    private ArrayList<Armas> armas = new ArrayList();
    private Random r = new Random();
    private Date d1;
    private Date d2;

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContra() {
        return contra;
    }

    public void setContra(String contra) {
        this.contra = contra;
    }

    @Override
    public String toString() {
        return "Main{" + "usuario=" + usuario + ", contra=" + contra + '}';
    }

    public Main(String usuario, String contra) {
        initComponents();
        this.usuario = usuario;
        this.contra = contra;
        jugadores.add(0, new Jugadores(this.usuario, this.contra));
    }

    public int finder(int[] ids, int id) {
        Arrays.sort(ids);
        int mid = ids.length / 2;
        System.out.println("MID " + mid);
        if (ids[ids.length - 1] == id) {
            return ids[ids.length - 1];
        } else if (ids[mid] < id) {
            int length = ids.length - mid;
            int[] temp = new int[length];
            for (int i = 0; i < length; i++) {
                temp[i] = ids[i + length - 1];
            }
            System.out.println(Arrays.toString(temp));
            System.out.println(ids[mid]);
            Arrays.sort(temp);
            return finder(temp, id);
        } else if (ids[mid] > id) {
            int length = ids.length - mid;
            int[] temp = new int[length];
            for (int i = 0; i < length; i++) {
                temp[i] = ids[length - i - 1];
            }
            System.out.println(Arrays.toString(temp));
            System.out.println(ids[mid]);
            Arrays.sort(temp);
            return finder(temp, id);
        } else {
            System.out.println(ids[mid]);
            return ids[mid];
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void generar() {
        jugadores.add(new Jugadores("CactusKevin", "eidfjay"));
        jugadores.add(new Jugadores("Sham", "oidyysnt"));
        jugadores.add(new Jugadores("kimberly", "danoaeysa"));

        armas.add(new Armas("LazarBeam", 30, 80));
        armas.add(new Armas("AR", 10, 90));
        armas.add(new Armas("Shawty", 20, 50));

        personajes.add(new Fortaleza("PeaceFinder", armas.get(0)));
        personajes.add(new Medico("AntiDeath", armas.get(1)));
        personajes.add(new Rastraeador("TrackerDUH", armas.get(2)));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_white = new javax.swing.JPanel();
        panelMain = new javax.swing.JTabbedPane();
        pan_Select = new javax.swing.JPanel();
        cb_personajes = new javax.swing.JComboBox<>();
        pan_seleccionar = new javax.swing.JPanel();
        label_seleccionar = new javax.swing.JLabel();
        pan_Jugar = new javax.swing.JPanel();
        pantalla = new javax.swing.JScrollPane();
        texto_partida = new javax.swing.JTextArea();
        label_restantes = new javax.swing.JLabel();
        botton_start = new javax.swing.JButton();
        field_atacar = new javax.swing.JFormattedTextField();
        boton_atacar = new javax.swing.JButton();
        pan_CrearPersonaje = new javax.swing.JPanel();
        label_nombre = new javax.swing.JLabel();
        label_vida = new javax.swing.JLabel();
        label_tipo = new javax.swing.JLabel();
        label_escudo = new javax.swing.JLabel();
        label_arma = new javax.swing.JLabel();
        label_nombreArma = new javax.swing.JLabel();
        label_precision = new javax.swing.JLabel();
        label_daño = new javax.swing.JLabel();
        label_ARMA = new javax.swing.JLabel();
        label_PERSONAJE = new javax.swing.JLabel();
        cb_armas = new javax.swing.JComboBox<>();
        text_nombre = new javax.swing.JTextField();
        textf_vida = new javax.swing.JFormattedTextField();
        textf_escudo = new javax.swing.JFormattedTextField();
        text_nombreArma = new javax.swing.JTextField();
        textf_precision = new javax.swing.JFormattedTextField();
        textf_daño = new javax.swing.JFormattedTextField();
        cb_tipo = new javax.swing.JComboBox<>();
        button_personaje = new javax.swing.JButton();
        button_arma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_white.setBackground(new java.awt.Color(255, 255, 255));

        panelMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelMainStateChanged(evt);
            }
        });

        cb_personajes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pan_seleccionar.setBackground(new java.awt.Color(0, 204, 0));
        pan_seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pan_seleccionarMouseClicked(evt);
            }
        });

        label_seleccionar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_seleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_seleccionar.setText("Seleccionar");

        javax.swing.GroupLayout pan_seleccionarLayout = new javax.swing.GroupLayout(pan_seleccionar);
        pan_seleccionar.setLayout(pan_seleccionarLayout);
        pan_seleccionarLayout.setHorizontalGroup(
            pan_seleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_seleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        pan_seleccionarLayout.setVerticalGroup(
            pan_seleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_seleccionarLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(label_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout pan_SelectLayout = new javax.swing.GroupLayout(pan_Select);
        pan_Select.setLayout(pan_SelectLayout);
        pan_SelectLayout.setHorizontalGroup(
            pan_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_SelectLayout.createSequentialGroup()
                .addGroup(pan_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_SelectLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cb_personajes, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_SelectLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(pan_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pan_SelectLayout.setVerticalGroup(
            pan_SelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_SelectLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb_personajes, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(69, 69, 69)
                .addComponent(pan_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        panelMain.addTab("tab1", pan_Select);

        texto_partida.setColumns(20);
        texto_partida.setRows(5);
        pantalla.setViewportView(texto_partida);

        label_restantes.setText("Restantes: 60");

        botton_start.setText("COMENZAR");
        botton_start.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                botton_startStateChanged(evt);
            }
        });
        botton_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botton_startMouseClicked(evt);
            }
        });

        field_atacar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        boton_atacar.setText("ATACAR");
        boton_atacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_atacarMouseClicked(evt);
            }
        });
        boton_atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_JugarLayout = new javax.swing.GroupLayout(pan_Jugar);
        pan_Jugar.setLayout(pan_JugarLayout);
        pan_JugarLayout.setHorizontalGroup(
            pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_JugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla)
                .addContainerGap())
            .addGroup(pan_JugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field_atacar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_atacar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_JugarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botton_start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(label_restantes)
                .addGap(58, 58, 58))
        );
        pan_JugarLayout.setVerticalGroup(
            pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_JugarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_restantes)
                    .addComponent(botton_start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pan_JugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_atacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_atacar))
                .addContainerGap())
        );

        panelMain.addTab("tab2", pan_Jugar);

        label_nombre.setText("Nombre");

        label_vida.setText("Vida");

        label_tipo.setText("Tipo");

        label_escudo.setText("Escudo");

        label_arma.setText("Arma");

        label_nombreArma.setText("Nombre");

        label_precision.setText("Precision");

        label_daño.setText("Daño");

        label_ARMA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_ARMA.setText("CREAR ARMA");

        label_PERSONAJE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_PERSONAJE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_PERSONAJE.setText("CREAR PERSONAJE");

        cb_armas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_armas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_armasActionPerformed(evt);
            }
        });

        textf_vida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        textf_escudo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        textf_precision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textf_precision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_precisionActionPerformed(evt);
            }
        });

        textf_daño.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        button_personaje.setText("Crear Personaje");
        button_personaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_personajeMouseClicked(evt);
            }
        });

        button_arma.setText("Crear Arma");
        button_arma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_armaMouseClicked(evt);
            }
        });
        button_arma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_armaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_CrearPersonajeLayout = new javax.swing.GroupLayout(pan_CrearPersonaje);
        pan_CrearPersonaje.setLayout(pan_CrearPersonajeLayout);
        pan_CrearPersonajeLayout.setHorizontalGroup(
            pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_CrearPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_precision)
                    .addComponent(label_ARMA)
                    .addComponent(label_PERSONAJE)
                    .addGroup(pan_CrearPersonajeLayout.createSequentialGroup()
                        .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textf_precision, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombreArma, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_escudo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textf_escudo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nombreArma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan_CrearPersonajeLayout.createSequentialGroup()
                                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_arma)
                                    .addComponent(label_daño))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pan_CrearPersonajeLayout.createSequentialGroup()
                                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textf_daño)
                                    .addComponent(cb_armas, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE)
                                    .addComponent(label_vida, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textf_vida, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pan_CrearPersonajeLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_tipo)
                                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_CrearPersonajeLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                        .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(button_arma)
                                            .addComponent(button_personaje))))))))
                .addGap(60, 60, 60))
        );
        pan_CrearPersonajeLayout.setVerticalGroup(
            pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_CrearPersonajeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(label_PERSONAJE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_vida)
                    .addComponent(label_nombre)
                    .addComponent(label_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_escudo)
                    .addComponent(label_arma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_armas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textf_escudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_personaje))
                .addGap(25, 25, 25)
                .addComponent(label_ARMA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_daño)
                    .addComponent(label_nombreArma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_CrearPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_arma)
                    .addComponent(text_nombreArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textf_daño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_precision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textf_precision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelMain.addTab("tab3", pan_CrearPersonaje);

        javax.swing.GroupLayout bg_whiteLayout = new javax.swing.GroupLayout(bg_white);
        bg_white.setLayout(bg_whiteLayout);
        bg_whiteLayout.setHorizontalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_whiteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        bg_whiteLayout.setVerticalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_whiteLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_white, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_white, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelMainStateChanged
        if (loocupo == 0) {
            generar();
            loocupo = 1;
        }
        if (panelMain.getSelectedIndex() == 0) {
            DefaultComboBoxModel m = new DefaultComboBoxModel();
            for (Personajes personaje : personajes) {
                m.addElement(personaje);
            }
            cb_personajes.setModel(m);
        }
        if (panelMain.getSelectedIndex() == 2) {
            DefaultComboBoxModel tipo = new DefaultComboBoxModel();
            tipo.addElement("Fortaleza");
            tipo.addElement("Medico");
            tipo.addElement("Rastreador");
            cb_tipo.setModel(tipo);

            DefaultComboBoxModel tipoArmas = new DefaultComboBoxModel();
            for (Armas arma : armas) {
                tipoArmas.addElement(arma);
            }
            cb_armas.setModel(tipoArmas);

        }
    }//GEN-LAST:event_panelMainStateChanged

    private void pan_seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_seleccionarMouseClicked
        jugadores.get(0).setPersonaje((Personajes) cb_personajes.getSelectedItem());
        panelMain.setSelectedIndex(1);
    }//GEN-LAST:event_pan_seleccionarMouseClicked

    private void botton_startStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botton_startStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_startStateChanged

    private void botton_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botton_startMouseClicked
        jugadores.get(0).setPersonaje((Personajes) cb_personajes.getSelectedItem());
        for (int i = 4; i < 60; i++) {
            jugadores.add(new Jugadores(personajes));
            for (int j = 0; j < jugadores.size(); j++) {
                if (jugadores.get(j).getId() == jugadores.get(i).getId()) {
                    jugadores.get(i).setId(0 + r.nextInt(1000));
                }
            }
        }
        for (Jugadores jugadore : jugadores) {
            texto_partida.append(jugadore.toString() + "\n");

        }
        d1 = new Date();
    }//GEN-LAST:event_botton_startMouseClicked

    private void boton_atacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_atacarActionPerformed

    private void boton_atacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_atacarMouseClicked
        int cont = 0;
        for (Jugadores jugadore : jugadores) {
            if (jugadore.getNombre()==(usuario)) {
                cont = 1;
            }
        }

        if (field_atacar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El jugador esta muerto o el ID no existe");
        } else if (cont == 0) {
            JOptionPane.showMessageDialog(this, "ESTAS MUERTO");
        } else {
            for (Jugadores jugadore : jugadores) {
                if (jugadore.getId() == Integer.parseInt(field_atacar.getText())) {
                    jugadores.get(0).getPersonaje().Atacar(jugadore.getPersonaje());
                    texto_partida.append(jugadores.get(0).getNombre() + "--->" + jugadore.getNombre() + "\n");
                    if (jugadore.getPersonaje().getVidatot() < 0) {
                        texto_partida.append(jugadores.get(0).getNombre() + " " + jugadores.get(0).getId() + " " + " MATO A " + jugadore.getNombre() + " " + jugadore.getId() + " " + "\n");
                        jugadores.remove(jugadore);
                    }
                }
            }
            int random1 = 1 + r.nextInt(jugadores.size() - 1);
            int random2 = r.nextInt(jugadores.size());
            for (int i = 0; i < 5; i++) {
                while (random1 == random2) {
                    random1 = 1 + r.nextInt(jugadores.size());
                    random2 = r.nextInt(jugadores.size());
                }
                random1 = 1 + r.nextInt(jugadores.size());
                random2 = r.nextInt(jugadores.size());
                jugadores.get(random1).getPersonaje().Atacar(jugadores.get(random2).getPersonaje());
                texto_partida.append(jugadores.get(random1).getNombre() + " " + jugadores.get(random1).getId() + " " + " ---> " + jugadores.get(random2).getNombre() + " " + jugadores.get(random2).getId() + " " + "\n");
                if (jugadores.get(random2).getPersonaje().getVidatot() <= 0) {
                    texto_partida.append(jugadores.get(random1).getNombre() + " " + jugadores.get(random1).getId() + " " + " MATO A " + jugadores.get(random2).getNombre() + " " + jugadores.get(random2).getId() + "\n");
                    jugadores.remove(jugadores.get(random2));
                }
                label_restantes.setText("Restantes: " + jugadores.size());
            }
            if (jugadores.size() == 1) {
                texto_partida.append(jugadores.get(0) + "HA GANADO\n");
                d2 = new Date();
                long tiempo = d2.getTime() - d1.getTime();
                long seconds = TimeUnit.SECONDS.toSeconds(tiempo);
                texto_partida.append("La partida duro: " + seconds);
            }

        }

    }//GEN-LAST:event_boton_atacarMouseClicked

    private void cb_armasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_armasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_armasActionPerformed

    private void textf_precisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_precisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_precisionActionPerformed

    private void button_armaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_armaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_armaActionPerformed

    private void button_personajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_personajeMouseClicked
        if (cb_tipo.getSelectedIndex() == 0) {
            personajes.add(new Fortaleza(text_nombre.getText(), Integer.parseInt(textf_vida.getText()), Integer.parseInt(textf_escudo.getText()), armas.get(cb_armas.getSelectedIndex())));
        } else if (cb_tipo.getSelectedIndex() == 1) {
            personajes.add(new Medico(text_nombre.getText(), Integer.parseInt(textf_vida.getText()), Integer.parseInt(textf_escudo.getText()), armas.get(cb_armas.getSelectedIndex())));
        } else if (cb_tipo.getSelectedIndex() == 2) {
            personajes.add(new Rastraeador(text_nombre.getText(), Integer.parseInt(textf_vida.getText()), Integer.parseInt(textf_escudo.getText()), armas.get(cb_armas.getSelectedIndex())));
        }
        JOptionPane.showMessageDialog(this, "Personaje Agregado Exitosamente");
        text_nombre.setText("");
        textf_vida.setText("");
        textf_escudo.setText("");

    }//GEN-LAST:event_button_personajeMouseClicked

    private void button_armaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_armaMouseClicked
        armas.add(new Armas(text_nombreArma.getText(), Integer.parseInt(textf_daño.getText()), Integer.parseInt(textf_precision.getText())));
        JOptionPane.showMessageDialog(this, "Arma Agregado Exitosamente");
        text_nombreArma.setText("");
        textf_daño.setText("");
        textf_precision.setText("");
    }//GEN-LAST:event_button_armaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main("bruh", "ksjdk").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_white;
    private javax.swing.JButton boton_atacar;
    private javax.swing.JButton botton_start;
    private javax.swing.JButton button_arma;
    private javax.swing.JButton button_personaje;
    private javax.swing.JComboBox<String> cb_armas;
    private javax.swing.JComboBox<String> cb_personajes;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JFormattedTextField field_atacar;
    private javax.swing.JLabel label_ARMA;
    private javax.swing.JLabel label_PERSONAJE;
    private javax.swing.JLabel label_arma;
    private javax.swing.JLabel label_daño;
    private javax.swing.JLabel label_escudo;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_nombreArma;
    private javax.swing.JLabel label_precision;
    private javax.swing.JLabel label_restantes;
    private javax.swing.JLabel label_seleccionar;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JLabel label_vida;
    private javax.swing.JPanel pan_CrearPersonaje;
    private javax.swing.JPanel pan_Jugar;
    private javax.swing.JPanel pan_Select;
    private javax.swing.JPanel pan_seleccionar;
    private javax.swing.JTabbedPane panelMain;
    private javax.swing.JScrollPane pantalla;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_nombreArma;
    private javax.swing.JFormattedTextField textf_daño;
    private javax.swing.JFormattedTextField textf_escudo;
    private javax.swing.JFormattedTextField textf_precision;
    private javax.swing.JFormattedTextField textf_vida;
    private javax.swing.JTextArea texto_partida;
    // End of variables declaration//GEN-END:variables
}
